name: Test Google Drive Access

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Optional: also run daily at midnight

jobs:
  test-drive:
    runs-on: ubuntu-latest  # GitHub provides this Ubuntu VM
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Gets your code from the repo
      
      - name: Set up Python
        uses: actions/setup-python@v4  # Installs Python
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
      
      - name: Create downloaded directory
        run: mkdir -p downloaded
      
      - name: Run Drive API test
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          python test_drive.py
      
      - name: Upload downloaded files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drive-files
          path: downloaded/
